#ifndef SNAKE_GAME_APP_CONFIG_H
#define SNAKE_GAME_APP_CONFIG_H

/*
 * 这些常量先服务 Phase 1 的界面骨架。
 * 后续游戏逻辑库会复用棋盘尺寸，确保渲染层和核心规则使用同一套网格坐标。
 */
#define SNAKE_WINDOW_WIDTH 960
#define SNAKE_WINDOW_HEIGHT 720

#define SNAKE_BOARD_COLUMNS 32
#define SNAKE_BOARD_ROWS 24
#define SNAKE_CELL_SIZE 24

#define SNAKE_BOARD_PIXEL_WIDTH (SNAKE_BOARD_COLUMNS * SNAKE_CELL_SIZE)
#define SNAKE_BOARD_PIXEL_HEIGHT (SNAKE_BOARD_ROWS * SNAKE_CELL_SIZE)

#define SNAKE_BOARD_ORIGIN_X ((SNAKE_WINDOW_WIDTH - SNAKE_BOARD_PIXEL_WIDTH) / 2)
#define SNAKE_BOARD_ORIGIN_Y 112

#endif
