<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { api, readableError } from '../../api/client'
import AsyncState from '../../components/AsyncState.vue'
import type { Submission } from '../../types'
import { safeDiagnostic, verdictLabel } from '../../utils/submissions'
const items=ref<Submission[]>([]);const selected=ref<Submission|null>(null);const state=ref<'loading'|'error'|'ready'>('loading');const error=ref('');const detailError=ref('');const failedDetailId=ref<number|null>(null);async function load(){state.value='loading';error.value='';try{items.value=(await api.get<Submission[]>('/admin/submissions')).data;state.value='ready'}catch(cause){error.value=readableError(cause,'提交管理列表加载失败');state.value='error'}}async function inspect(id:number){detailError.value='';failedDetailId.value=null;try{selected.value=(await api.get<Submission>(`/admin/submissions/${id}`)).data}catch(cause){selected.value=null;failedDetailId.value=id;detailError.value=readableError(cause,'提交详情加载失败')}}onMounted(load)
</script>
<template><div><div class="page-heading"><div><p class="eyebrow">评测审查</p><h1 tabindex="-1">提交管理</h1><p>管理员可查看完整源码与安全诊断信息。</p></div></div><AsyncState v-if="state!=='ready'" :status="state" :message="state==='loading'?'正在加载提交…':error" :on-retry="load"/><div v-else><div v-if="detailError" class="feedback error" role="alert">{{detailError}} <button v-if="failedDetailId!==null" class="button button-secondary" type="button" @click="inspect(failedDetailId)">重新查看详情</button></div><div class="admin-submission-layout"><section class="card table-wrap"><table><thead><tr><th scope="col">编号</th><th scope="col">用户</th><th scope="col">题目</th><th scope="col">结果</th><th scope="col">操作</th></tr></thead><tbody><tr v-for="item in items" :key="item.id"><td>#{{item.id}}</td><td>{{item.user_id}}</td><td>{{item.problem_id}}</td><td><span :class="['verdict',`verdict-${item.status.toLowerCase()}`]">{{verdictLabel[item.status]}}</span></td><td><button class="button button-secondary" type="button" @click="inspect(item.id)">查看详情</button></td></tr></tbody></table><AsyncState v-if="!items.length" status="empty" message="还没有提交记录。"/></section><aside v-if="selected" class="card submission-inspector"><h2>提交 #{{selected.id}}</h2><dl><div><dt>诊断</dt><dd>{{safeDiagnostic(selected)}}</dd></div><div><dt>失败测试点</dt><dd>{{selected.failed_case??'—'}}</dd></div><div><dt>运行时间</dt><dd>{{selected.runtime_ms==null?'—':`${selected.runtime_ms} ms`}}</dd></div></dl><h3>源码</h3><pre class="source-code"><code>{{selected.source}}</code></pre></aside></div></div></div></template>
